"""
Report Generator Agent
Creates structured, professional research reports in Markdown and PDF formats.
"""

import os
import json
from datetime import datetime
from typing import Optional, List
from langchain_core.messages import HumanMessage, SystemMessage
from app.services.llm_service import get_llm
from app.utils.logger import get_logger

logger = get_logger(__name__)

REPORTS_DIR = os.getenv("REPORTS_DIR", "./data/reports")

REPORT_SYSTEM_PROMPT = """You are an expert Research Report Writer. Create a comprehensive, 
professional research report in Markdown format.

Structure your report with:
# [TITLE]

## Executive Summary
Brief 2-3 sentence overview of key findings.

## Research Overview
Background and scope of research.

## Key Findings
Numbered list of major discoveries with analysis.

## Detailed Analysis
In-depth analysis organized by theme/topic.

## Key Insights
Bullet points of actionable insights.

## Limitations & Uncertainties
What we don't know or couldn't verify.

## Conclusion
Summary and implications.

## References & Sources
Citations if available.

---
*Generated by Multi-Agent AI Research Assistant*

Use professional academic/business report language. Be thorough and precise."""


class ReportGeneratorAgent:
    """
    Report Generator Agent: Creates polished research reports.
    Supports Markdown and PDF output formats.
    """

    def __init__(self):
        self.llm = get_llm()
        self.name = "Report Generator"
        os.makedirs(REPORTS_DIR, exist_ok=True)

    async def generate_report(
        self,
        query: str,
        research_findings: str,
        critique_data: Optional[dict] = None,
        plan: Optional[dict] = None,
        sources: Optional[List[dict]] = None,
    ) -> dict:
        """
        Generate a comprehensive research report.
        
        Returns:
            Dict with report content, file paths, and metadata
        """
        logger.info(f"📄 Report Agent: Generating report for: {query[:80]}...")

        # Build context for report generation
        context_parts = [f"Research Query: {query}", f"\nResearch Findings:\n{research_findings}"]

        if critique_data:
            score = critique_data.get("final_quality_score", 0)
            context_parts.append(f"\nQuality Score: {score}/10")
            context_parts.append(f"Reflection Iterations: {critique_data.get('total_iterations', 1)}")

        if sources:
            source_list = "\n".join(
                f"- {s.get('metadata', {}).get('filename', 'Unknown')} (relevance: {s.get('relevance_score', 0):.2f})"
                for s in sources[:5]
            )
            context_parts.append(f"\nSources Used:\n{source_list}")

        full_context = "\n".join(context_parts)

        messages = [
            SystemMessage(content=REPORT_SYSTEM_PROMPT),
            HumanMessage(
                content=f"{full_context}\n\nGenerate a comprehensive research report based on the above."
            ),
        ]

        try:
            response = await self.llm.ainvoke(messages)
            report_content = response.content if hasattr(response, "content") else str(response)

            # Save markdown report
            report_id = datetime.now().strftime("%Y%m%d_%H%M%S")
            md_filename = f"report_{report_id}.md"
            md_path = os.path.join(REPORTS_DIR, md_filename)

            with open(md_path, "w", encoding="utf-8") as f:
                f.write(report_content)

            # Generate PDF
            pdf_path = None
            try:
                pdf_path = await self._generate_pdf(report_content, report_id)
            except Exception as e:
                logger.warning(f"PDF generation failed: {e}")

            logger.info(f"✅ Report Agent: Report generated: {md_filename}")

            return {
                "content": report_content,
                "markdown_path": md_path,
                "pdf_path": pdf_path,
                "report_id": report_id,
                "filename": md_filename,
                "word_count": len(report_content.split()),
                "generated_at": datetime.utcnow().isoformat(),
            }

        except Exception as e:
            logger.error(f"Report generation error: {e}")
            # Generate minimal report
            content = self._minimal_report(query, research_findings)
            return {
                "content": content,
                "report_id": "error",
                "error": str(e),
                "generated_at": datetime.utcnow().isoformat(),
            }

    async def _generate_pdf(self, markdown_content: str, report_id: str) -> str:
        """Convert markdown report to PDF using ReportLab."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.enums import TA_LEFT
            import re

            pdf_filename = f"report_{report_id}.pdf"
            pdf_path = os.path.join(REPORTS_DIR, pdf_filename)

            doc = SimpleDocTemplate(pdf_path, pagesize=letter, topMargin=inch)
            styles = getSampleStyleSheet()
            story = []

            # Process markdown line by line
            for line in markdown_content.split("\n"):
                line = line.strip()
                if not line:
                    story.append(Spacer(1, 12))
                elif line.startswith("# "):
                    story.append(Paragraph(line[2:], styles["Title"]))
                elif line.startswith("## "):
                    story.append(Paragraph(line[3:], styles["Heading2"]))
                elif line.startswith("### "):
                    story.append(Paragraph(line[4:], styles["Heading3"]))
                elif line.startswith("- ") or line.startswith("* "):
                    story.append(Paragraph(f"• {line[2:]}", styles["Normal"]))
                else:
                    # Clean markdown formatting
                    clean = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
                    clean = re.sub(r"\*(.*?)\*", r"\1", clean)
                    if clean:
                        story.append(Paragraph(clean, styles["Normal"]))

            doc.build(story)
            return pdf_path

        except Exception as e:
            logger.error(f"PDF generation error: {e}")
            raise

    def _minimal_report(self, query: str, findings: str) -> str:
        """Generate a minimal report when LLM fails."""
        return f"""# Research Report

**Query:** {query}

**Generated:** {datetime.utcnow().isoformat()}

## Findings

{findings}

---
*Generated by Multi-Agent AI Research Assistant*
"""
